os: xenial # Ubuntu 16.04.7 LTS
language: python
cache: pip
python:
  # Python versions
  - "3.6"
  - "3.9-dev"  # Development branch
# Allow modifications
matrix:
  allow_failures:
      - python: "3.9-dev"
# Install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -U pytest
# Run tests
script:
  - pytest
