name: Simple Python Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Action workflow to checkout the repository
      - name: Checkout the code repository
        uses: actions/checkout@v2
      # Action workflow to Install and setup python version in the local github-workspace
      - name: Install python version
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit test cases with PyTest
        run: pytest
